// ─────────────────────────────────────────────────────────────────────────────
// Error Code Constants
// Pattern: [CATEGORY]_[SPECIFIC]_[HTTP_STATUS]
// ─────────────────────────────────────────────────────────────────────────────

export const ErrorCodes = {
  // ── AUTH ──────────────────────────────────────────────────────────────────
  AUTH_TOKEN_EXPIRED_401: "AUTH_TOKEN_EXPIRED_401",
  AUTH_TOKEN_INVALID_401: "AUTH_TOKEN_INVALID_401",
  AUTH_TOKEN_MISSING_401: "AUTH_TOKEN_MISSING_401",
  AUTH_REFRESH_TOKEN_INVALID_401: "AUTH_REFRESH_TOKEN_INVALID_401",
  AUTH_INSUFFICIENT_PERMISSIONS_403: "AUTH_INSUFFICIENT_PERMISSIONS_403",
  AUTH_ACCOUNT_LOCKED_403: "AUTH_ACCOUNT_LOCKED_403",
  AUTH_ACCOUNT_SUSPENDED_403: "AUTH_ACCOUNT_SUSPENDED_403",
  AUTH_SESSION_EXPIRED_401: "AUTH_SESSION_EXPIRED_401",
  AUTH_MFA_REQUIRED_403: "AUTH_MFA_REQUIRED_403",
  AUTH_MFA_INVALID_401: "AUTH_MFA_INVALID_401",
  AUTH_WALLET_NOT_VERIFIED_403: "AUTH_WALLET_NOT_VERIFIED_403",
  AUTH_SIGNATURE_INVALID_401: "AUTH_SIGNATURE_INVALID_401",

  // ── VALIDATION ────────────────────────────────────────────────────────────
  VALIDATION_REQUIRED_FIELD_400: "VALIDATION_REQUIRED_FIELD_400",
  VALIDATION_INVALID_FORMAT_400: "VALIDATION_INVALID_FORMAT_400",
  VALIDATION_OUT_OF_RANGE_400: "VALIDATION_OUT_OF_RANGE_400",
  VALIDATION_DUPLICATE_VALUE_409: "VALIDATION_DUPLICATE_VALUE_409",
  VALIDATION_INVALID_ADDRESS_400: "VALIDATION_INVALID_ADDRESS_400",
  VALIDATION_SCHEMA_MISMATCH_400: "VALIDATION_SCHEMA_MISMATCH_400",
  VALIDATION_CONSTRAINT_VIOLATED_422: "VALIDATION_CONSTRAINT_VIOLATED_422",
  VALIDATION_INVALID_ENUM_400: "VALIDATION_INVALID_ENUM_400",
  VALIDATION_MAX_LENGTH_400: "VALIDATION_MAX_LENGTH_400",
  VALIDATION_MIN_LENGTH_400: "VALIDATION_MIN_LENGTH_400",
  VALIDATION_PAYLOAD_TOO_LARGE_413: "VALIDATION_PAYLOAD_TOO_LARGE_413",
  VALIDATION_UNSUPPORTED_MEDIA_415: "VALIDATION_UNSUPPORTED_MEDIA_415",

  // ── BLOCKCHAIN ────────────────────────────────────────────────────────────
  BLOCKCHAIN_TX_FAILED_500: "BLOCKCHAIN_TX_FAILED_500",
  BLOCKCHAIN_TX_REVERTED_400: "BLOCKCHAIN_TX_REVERTED_400",
  BLOCKCHAIN_INSUFFICIENT_GAS_400: "BLOCKCHAIN_INSUFFICIENT_GAS_400",
  BLOCKCHAIN_NONCE_TOO_LOW_400: "BLOCKCHAIN_NONCE_TOO_LOW_400",
  BLOCKCHAIN_CONTRACT_NOT_FOUND_404: "BLOCKCHAIN_CONTRACT_NOT_FOUND_404",
  BLOCKCHAIN_NETWORK_ERROR_503: "BLOCKCHAIN_NETWORK_ERROR_503",
  BLOCKCHAIN_RPC_TIMEOUT_504: "BLOCKCHAIN_RPC_TIMEOUT_504",
  BLOCKCHAIN_INVALID_SIGNATURE_400: "BLOCKCHAIN_INVALID_SIGNATURE_400",
  BLOCKCHAIN_INSUFFICIENT_FUNDS_402: "BLOCKCHAIN_INSUFFICIENT_FUNDS_402",
  BLOCKCHAIN_BLOCK_NOT_FOUND_404: "BLOCKCHAIN_BLOCK_NOT_FOUND_404",
  BLOCKCHAIN_REORG_DETECTED_503: "BLOCKCHAIN_REORG_DETECTED_503",
  BLOCKCHAIN_SIMULATION_FAILED_400: "BLOCKCHAIN_SIMULATION_FAILED_400",

  // ── AI_SERVICE ────────────────────────────────────────────────────────────
  AI_SERVICE_UNAVAILABLE_503: "AI_SERVICE_UNAVAILABLE_503",
  AI_SERVICE_TIMEOUT_504: "AI_SERVICE_TIMEOUT_504",
  AI_SERVICE_QUOTA_EXCEEDED_429: "AI_SERVICE_QUOTA_EXCEEDED_429",
  AI_SERVICE_MODEL_NOT_FOUND_404: "AI_SERVICE_MODEL_NOT_FOUND_404",
  AI_SERVICE_INVALID_PROMPT_400: "AI_SERVICE_INVALID_PROMPT_400",
  AI_SERVICE_CONTENT_FILTERED_422: "AI_SERVICE_CONTENT_FILTERED_422",
  AI_SERVICE_RESPONSE_INVALID_502: "AI_SERVICE_RESPONSE_INVALID_502",
  AI_SERVICE_COMPUTE_FAILED_500: "AI_SERVICE_COMPUTE_FAILED_500",

  // ── DATABASE ──────────────────────────────────────────────────────────────
  DATABASE_CONNECTION_FAILED_503: "DATABASE_CONNECTION_FAILED_503",
  DATABASE_QUERY_TIMEOUT_504: "DATABASE_QUERY_TIMEOUT_504",
  DATABASE_RECORD_NOT_FOUND_404: "DATABASE_RECORD_NOT_FOUND_404",
  DATABASE_UNIQUE_VIOLATION_409: "DATABASE_UNIQUE_VIOLATION_409",
  DATABASE_FK_VIOLATION_409: "DATABASE_FK_VIOLATION_409",
  DATABASE_TRANSACTION_FAILED_500: "DATABASE_TRANSACTION_FAILED_500",
  DATABASE_MIGRATION_FAILED_500: "DATABASE_MIGRATION_FAILED_500",
  DATABASE_POOL_EXHAUSTED_503: "DATABASE_POOL_EXHAUSTED_503",
  DATABASE_READ_ONLY_503: "DATABASE_READ_ONLY_503",

  // ── RATE_LIMIT ────────────────────────────────────────────────────────────
  RATE_LIMIT_EXCEEDED_429: "RATE_LIMIT_EXCEEDED_429",
  RATE_LIMIT_IP_BLOCKED_429: "RATE_LIMIT_IP_BLOCKED_429",
  RATE_LIMIT_USER_BLOCKED_429: "RATE_LIMIT_USER_BLOCKED_429",
  RATE_LIMIT_API_KEY_BLOCKED_429: "RATE_LIMIT_API_KEY_BLOCKED_429",
  RATE_LIMIT_BURST_EXCEEDED_429: "RATE_LIMIT_BURST_EXCEEDED_429",
  RATE_LIMIT_QUOTA_EXHAUSTED_429: "RATE_LIMIT_QUOTA_EXHAUSTED_429",

  // ── EXTERNAL ──────────────────────────────────────────────────────────────
  EXTERNAL_SERVICE_UNAVAILABLE_503: "EXTERNAL_SERVICE_UNAVAILABLE_503",
  EXTERNAL_SERVICE_TIMEOUT_504: "EXTERNAL_SERVICE_TIMEOUT_504",
  EXTERNAL_SERVICE_AUTH_FAILED_502: "EXTERNAL_SERVICE_AUTH_FAILED_502",
  EXTERNAL_SERVICE_RATE_LIMITED_429: "EXTERNAL_SERVICE_RATE_LIMITED_429",
  EXTERNAL_SERVICE_INVALID_RESP_502: "EXTERNAL_SERVICE_INVALID_RESP_502",
  EXTERNAL_WEBHOOK_FAILED_500: "EXTERNAL_WEBHOOK_FAILED_500",
  EXTERNAL_ORACLE_UNAVAILABLE_503: "EXTERNAL_ORACLE_UNAVAILABLE_503",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** Extract the HTTP status suffix from an error code string */
export function extractHttpStatus(code: ErrorCode): number {
  const parts = code.split("_");
  return parseInt(parts[parts.length - 1], 10);
}

/** Extract the category prefix from an error code string */
export function extractCategory(code: ErrorCode): string {
  return code.split("_")[0];
}
